# MySQL config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cloudinary
CLOUDINARY_URL=${CLOUDINARY_KEY}

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Logging
logging.level.root=INFO
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
logging.pattern.file="%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.file.name=Logs/api-blog.log
logging.file.max-size=10MB
logging.file.max-history=30


# redis
spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}


# JWT
jwt.secret.key=${JWT_SECRET}