CREATE TABLE IF NOT EXISTS posts(

    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    message VARCHAR(255) NOT NULL,
    image_url VARCHAR(50),
    likes BIGINT DEFAULT 0,

    user_id BIGINT NOT NULL,

    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    active BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_user_post FOREIGN KEY (user_id) REFERENCES users(id)
);